# Optional: Use only if deploying to CodeDeploy
version: 0.0
Resources:
  - myApp:
      Type: AWS::EKS::Application
      Properties:
        Name: brain-tasks-app
        ClusterName: brain-tasks-apps
        Namespace: default

        FileExistsBehavior: OVERWRITE
