version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$ACCOUNT_ID
      - REGION=$REGION
      - REPO_NAME=$REPO_NAME
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME:latest
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - curl -o kubectl https://amazon-eks.s3.us-east-1.amazonaws.com/1.29.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - aws eks update-kubeconfig --region us-east-1 --name brain-tasks-app
     
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $IMAGE_URI
      - echo "Writing Kubernetes manifests..."
      - sed -i "s|<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/brain-tasks-app:latest|$IMAGE_URI|" k8s/deployment.yaml
      
      - kubectl apply -f k8s/deployment.yaml 
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - k8s/*.yaml
    - buildspec.yml
